### ISSUE TITLE
Pandas and pysimplegui

### ISSUE THREAD

**Issue by ModDayHippie** [ModDayHippie/DnD-Character-Sheet#5]
need to figure out how to make the pysimplegui keys work with pandas

**Comment by mathewrtaylor** [comment]
Got at this late, but a couple of suggestions:

Make your buttons into functions like this as an example:

```
def make_armour_win() -> None:
    """
    This function shows the Armour window

    :return: None

    :note: This function is called by clicking the 'Armor' button in the main window.
    """
    armour_df = pd.read_csv('Armour.csv')
    armour_df = armour_df.fillna('-')
    sg.popup_scrolled(armour_df, title='Armour', size=(125, 50))
```
Then in your True loop:
```
if event == ('Armor'):
        make_armour_win()
```
Ods and Excel files are made for humans, and python (and pandas are much happier read csv files). I've mocked up an example of your Armour.ods file, and added gold conversions for everything.

As for loading here's the same example using the ODS load, so you can see the difference:

```
def make_armour_win() -> None:
    """
    This function shows the Armour window

    :return: None

    :note: This function is called by clicking the 'Armor' button in the main window.
    """
    armour_df = pd.read_excel('Amour.ods', engine='odf', sheet_name='Sheet1', header=0, usecols=['Name', 'Price', 'AC', 'Weight', 'Stealth', 'Strength'])
    armour_df = armour_df.fillna('-')
    sg.popup_scrolled(armour_df, title='Armour', size=(125, 50))
```
Also the popup is a quick cheat I came across, I'm sure there's a better way to do it, but wanted to have something at least working to show you. I took a skim through this, which was helpful: [https://www.youtube.com/watch?v=LzCfNanQ_9c](url)

I've included a copy of the converted file below.

Hope this helps, and totally open to helping you through this.

[Armour.csv](https://github.com/ModDayHippie/DnD-Character-Sheet/files/14661711/Armour.csv)
